// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkr_J-fFt5qTibNbodHaeSyWJvWHC6LYM',
    appId: '1:829052305775:web:0eebcbef24542e0227a89a',
    messagingSenderId: '829052305775',
    projectId: 'reddit-clone-3a561',
    authDomain: 'reddit-clone-3a561.firebaseapp.com',
    storageBucket: 'reddit-clone-3a561.appspot.com',
    measurementId: 'G-ZX3RXWMW2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXj6XUDTs7ccFMmQuAueFuqCGIkxdkcMk',
    appId: '1:829052305775:android:fe48eaa0d412ef3e27a89a',
    messagingSenderId: '829052305775',
    projectId: 'reddit-clone-3a561',
    storageBucket: 'reddit-clone-3a561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPJ9buZBLh-UpMV4qTFtZ-9ChRx9_UcY',
    appId: '1:829052305775:ios:f80a1cfa98701d5727a89a',
    messagingSenderId: '829052305775',
    projectId: 'reddit-clone-3a561',
    storageBucket: 'reddit-clone-3a561.appspot.com',
    iosClientId: '829052305775-sssauk6tueurco374508pr690s39g8c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneApp',
  );
}
